{
  "instructions": [
    "let parseAssertElemStr = await page.$(\"a\");\nif (parseAssertElemStr === null) { throw '\"a\" not found'; }\nawait page.evaluate(e => {\n    const errors = [];\n    const value = \"b\";\n    if (browserUiTestHelpers.elemTextContains(e, value)) {\n        errors.push(\"`\" + browserUiTestHelpers.getElemText(e, value) + \"` contains `\" + value + \"` (for CONTAINS check)\");\n    }\n    if (browserUiTestHelpers.elemTextEndsWith(e, value)) {\n        errors.push(\"`\" + browserUiTestHelpers.getElemText(e, value) + \"` ends with `\" + value + \"` (for ENDS_WITH check)\");\n    }\n    if (errors.length !== 0) {\n        const errs = errors.join(\", \");\n        throw \"The following errors happened: [\" + errs + \"]\";\n    }\n}, parseAssertElemStr);"
  ],
  "wait": false,
  "checkResult": true
}
