instructions = [
  """let parseAssertElemStr = await page.$(\"a\");
if (parseAssertElemStr === null) { throw '\"a\" not found'; }
await page.evaluate(e => {
    const errors = [];
    const value = \"b\";
    if (browserUiTestHelpers.elemTextContains(e, value)) {
        errors.push(\"`\" + browserUiTestHelpers.getElemText(e, value) + \"` contains `\" + value + \"` (for CONTAINS check)\");
    }
    if (browserUiTestHelpers.elemTextEndsWith(e, value)) {
        errors.push(\"`\" + browserUiTestHelpers.getElemText(e, value) + \"` ends with `\" + value + \"` (for ENDS_WITH check)\");
    }
    if (errors.length !== 0) {
        const errs = errors.join(\", \");
        throw \"The following errors happened: [\" + errs + \"]\";
    }
}, parseAssertElemStr);""",
]
wait = false
checkResult = true
warnings = [
  """`CONTAINS` is present more than once in the third argument array""",
]
