{
  "instructions": [
    "let parseAssertElemProp = await page.$(\"a ::after\");\nif (parseAssertElemProp === null) { throw '\"a ::after\" not found'; }\nawait page.evaluate(e => {\n    const nonMatchingProps = [];\n    const parseAssertElemPropDict = {\"a\":\"1\"};\n    for (const [parseAssertElemPropKey, parseAssertElemPropValue] of Object.entries(parseAssertElemPropDict)) {\n        if (e[parseAssertElemPropKey] === undefined) {\n            nonMatchingProps.push('Unknown property `' + parseAssertElemPropKey + '`');\n            continue;\n        }\n        if (String(e[parseAssertElemPropKey]) != parseAssertElemPropValue) {\n            nonMatchingProps.push('Expected `' + parseAssertElemPropValue + '` for property `' + parseAssertElemPropKey + '`, found `' + e[parseAssertElemPropKey] + '`');\n        }\n    }\n    if (nonMatchingProps.length !== 0) {\n        const props = nonMatchingProps.join(\", \");\n        throw \"The following errors happened (for selector `a ::after`): [\" + props + \"]\";\n    }\n}, parseAssertElemProp);"
  ],
  "wait": false,
  "warnings": [],
  "checkResult": true
}
